---

- name: Connect Azure Kubernetes Service
  hosts: localhost
  connection: local
  tasks:
    - name: cluster subscription 
      shell: az account set --subscription xxxxxxx 




    - name: Download cluster credentials 
      shell: az aks get-credentials --resource-group xxxxx --name xxxxx 





    - name: List all deployment
      shell: kubectl get deployments --all-namespaces=true
      register: result


    - debug: var=result.stdout_lines
