---

- name: ISTIO Install 
  hosts: localhost
  connection: local
  tasks:
    - name: Configure Helm Repository 
      shell: |
        helm repo add istio https://istio-release.storage.googleapis.com/charts
        helm repo update
      register: output1 
    - debug: var=output1.stdout_lines


    - name: Create Namespace 
      shell: kubectl create namespace istio-system 
      register: output2 
    - debug: var=output2.stdout_lines


    - name: Install base chart 
      shell: helm install istio-base istio/base -n istio-system --set defaultRevision=default
      register: output3 
    - debug: var=output3.stdout_lines


    - name: Validate 
      shell: helm ls -n istio-system
      register: output4 
    - debug: var=output4.stdout_lines


    - name: Install ISTIO Discovery Chart 
      shell: helm install istiod istio/istiod -n istio-system --wait
      register: output5 
    - debug: var=output5.stdout_lines


    - name: Get Status 
      shell: helm status istiod -n istio-system 
      register: output6 
    - debug: var=output6.stdout_lines


    - name: Check service 
      shell: kubectl get deployments -n istio-system --output wide 
      register: output7 
    - debug: var=output7.stdout_lines


    - name: Install Ingress Gateway 
      shell: |
        kubectl create namespace istio-ingress
        helm install istio-ingress istio/gateway -n istio-ingress --wait 
      register: output8 
    - debug: var=output8.stdout_lines


    - name: List all deployment
      shell: kubectl get deployments --all-namespaces=true
      register: result
    - debug: var=result.stdout_lines
